# Estágio 1: Build do aplicativo Angular
FROM node:18.20.4 as build

WORKDIR /app

COPY package.json package-lock.json /app/

RUN npm install

COPY . /app/

RUN npm run build --prod

# Estágio 2: Servir o aplicativo com Nginx
FROM nginx:latest

COPY --from=build /app/dist/angular-estrutura /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
