# Use uma imagem Nginx para servir a aplicação Angular
FROM nginx:alpine

# Copy the build output to the Nginx html directory
COPY ./dist/angular-estrutura /usr/share/nginx/html

# Copy the custom Nginx configuration file (if you have one)
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
